server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /client.apk {
        alias /usr/share/nginx/html/mobile_builds/client.apk;
        
        add_header Content-Type application/vnd.android.package-archive;
        add_header Content-Disposition "attachment; filename=client.apk";
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location /client.ipa {
        alias /usr/share/nginx/html/mobile_builds/client.ipa;
        add_header Content-Disposition "attachment; filename=client.ipa";
    }
}